"""add metric entries

Revision ID: cc4a568f3e38
Revises: 1a7579ff274a
Create Date: 2026-10-10 22:38:10.871146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4a568f3e38'
down_revision: Union[str, Sequence[str], None] = '1a7579ff274a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_entries',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(length=60), nullable=False),
    sa.Column('spend_cents', sa.BigInteger(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('revenue_cents', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_metric_entries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_entries'))
    )
    op.create_index(op.f('ix_metric_entries_project_id'), 'metric_entries', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_entries_project_id'), table_name='metric_entries')
    op.drop_table('metric_entries')
    # ### end Alembic commands ###
