"""add audience exclusions to projects

Revision ID: 1a7579ff274a
Revises: 36d38e5d4edf
Create Date: 2026-10-06 11:48:37.793804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7579ff274a'
down_revision: Union[str, Sequence[str], None] = '36d38e5d4edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('audience_exclusions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'audience_exclusions')
    # ### end Alembic commands ###
