"""add campaign items and revisions

Revision ID: 36d38e5d4edf
Revises: fa5b8f2fc022
Create Date: 2026-10-06 11:36:21.290867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36d38e5d4edf'
down_revision: Union[str, Sequence[str], None] = 'fa5b8f2fc022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_items',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_campaign_items_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_items'))
    )
    op.create_index(op.f('ix_campaign_items_project_id'), 'campaign_items', ['project_id'], unique=False)
    op.create_index('uq_campaign_items_live_key', 'campaign_items', ['project_id', 'kind', 'key'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('revisions',
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('restored_from', sa.Integer(), nullable=True),
    sa.Column('project_version', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['campaign_items.id'], name=op.f('fk_revisions_item_id_campaign_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], name=op.f('fk_revisions_job_id_ai_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_revisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revisions')),
    sa.UniqueConstraint('item_id', 'number', name=op.f('uq_revisions_item_id'))
    )
    op.create_index(op.f('ix_revisions_item_id'), 'revisions', ['item_id'], unique=False)
    op.create_index(op.f('ix_revisions_project_id'), 'revisions', ['project_id'], unique=False)
    op.add_column('ai_jobs', sa.Column('target', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'version')
    op.drop_column('ai_jobs', 'target')
    op.drop_index(op.f('ix_revisions_project_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_item_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index('uq_campaign_items_live_key', table_name='campaign_items', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index(op.f('ix_campaign_items_project_id'), table_name='campaign_items')
    op.drop_table('campaign_items')
    # ### end Alembic commands ###
