"""add user role and ai engine to briefs

Revision ID: a65e19b29ef8
Revises: 620f9baddb48
Create Date: 2026-10-05 12:02:19.256398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65e19b29ef8'
down_revision: Union[str, Sequence[str], None] = '620f9baddb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefs', sa.Column('user_role', sa.String(length=32), nullable=True))
    op.add_column('briefs', sa.Column('ai_engine', sa.String(length=32), server_default='claude', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('briefs', 'ai_engine')
    op.drop_column('briefs', 'user_role')
    # ### end Alembic commands ###
