"""Private file storage.

One small interface with two backends: the local disk for development, and any
S3-compatible bucket (Supabase Storage now, S3 later) for deployment. Nothing outside
this module knows which one is in use.
"""

import logging
from functools import lru_cache
from pathlib import Path
from typing import Protocol

from fastapi import HTTPException

from app.config import get_settings


log = logging.getLogger(__name__)


class StorageError(Exception):
    """Storage is unreachable or refused the operation."""


class Storage(Protocol):
    def save(self, key: str, data: bytes, content_type: str) -> None: ...
    def read(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalStorage:
    """Files under backend/uploads/. Development only: it does not survive a redeploy."""

    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # Keys are generated by this app, never by a user, but a traversal here would be
        # severe enough to be worth refusing outright.
        if not path.is_relative_to(self.root):
            raise StorageError("Invalid storage key.")
        return path

    def save(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def read(self, key: str) -> bytes:
        try:
            return self._path(key).read_bytes()
        except FileNotFoundError as e:
            raise StorageError("File not found.") from e

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


class S3Storage:
    """Any S3-compatible bucket. Objects stay private; the API streams them to the owner."""

    def __init__(self, bucket: str, endpoint_url: str, region: str, access_key: str, secret_key: str) -> None:
        import boto3  # imported here so local development needs no AWS packages loaded

        self.bucket = bucket
        self.client = boto3.client(
            "s3",
            endpoint_url=endpoint_url or None,
            region_name=region or None,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
        )

    def save(self, key: str, data: bytes, content_type: str) -> None:
        try:
            self.client.put_object(Bucket=self.bucket, Key=key, Body=data, ContentType=content_type)
        except Exception as e:  # noqa: BLE001 - any client error is the same to the caller
            raise StorageError("Could not store the file.") from e

    def read(self, key: str) -> bytes:
        try:
            return self.client.get_object(Bucket=self.bucket, Key=key)["Body"].read()
        except Exception as e:  # noqa: BLE001
            raise StorageError("File not found.") from e

    def delete(self, key: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=key)
        except Exception as e:  # noqa: BLE001
            raise StorageError("Could not delete the file.") from e


@lru_cache
def get_storage() -> Storage:
    settings = get_settings()
    if settings.storage_backend == "s3":
        return S3Storage(
            bucket=settings.s3_bucket,
            endpoint_url=settings.s3_endpoint_url,
            region=settings.s3_region,
            access_key=settings.s3_access_key_id,
            secret_key=settings.s3_secret_access_key,
        )
    return LocalStorage(Path(__file__).resolve().parent.parent / "uploads")


def storage_error() -> HTTPException:
    """One message for the user; the cause stays in the server logs."""
    return HTTPException(status_code=502, detail="File storage is unavailable. Please try again.")


def delete_quietly(storage: Storage, keys: list[str]) -> None:
    """Remove stored files whose rows are already gone. A failure is logged, not raised:
    the user's delete has happened, and an error page would suggest it hadn't."""
    for key in keys:
        try:
            storage.delete(key)
        except StorageError:
            log.warning("Could not delete stored file %s", key)
